### PR TITLE
Feature/PAI-69 & PAI-70 Learning Center

### PR DESCRIPTION
**Pull request by iSupercell**
PR for PAI-69 and PAI-70 Learning Center

Test URLs:

- Before: https://main--pricefx-eds--pricefx.hlx.live/
- After: https://feature-pai-70-learning-center-filter--pricefx-eds--pricefx.hlx.live/style-guide/components/learning-center

### CODE REVIEW

**Comment by amogh-daryapurkar** [comment]
@iSupercell Can we address the below issues?

- [ ] The search icon looks off on the learning center
- [ ] Can we ensure the tag shown on the cards is picked from Content Type, which means the category from JSON?
- [ ] Can we change query pageNum to page?

**Review by amogh-daryapurkar — CHANGES_REQUESTED** [review]
@iSupercell I added a comment on PR. Can you check?

**Comment by iSupercell** [comment]
> * [ ]  Can we ensure the tag shown on the cards is picked from Content Type, which means the category from JSON?

Hi @amogh-daryapurkar sorry I just need a bit more clarification. Are you referring to the purple-ish eyebrow text above the card's title? Change that to only pick up `pricefx:content-types/<keyword>` from the `cq-tags` on the json? Right now I see the json data returns list of `pricefx:category/<keyword>` for the `category` key. So that's not the key I filter for the "Filter by Content Type" and it should filter from `cq-tags` instead?

**Comment by iSupercell** [comment]
@amogh-daryapurkar To make sure I'm understanding it correctly we can take this Article 17 as example:
```{
"path": "[/learning-center/article-17](https://main--pricefx-eds--pricefx.hlx.page/learning-center/article-17)",
"lastModified": 1714454795,
"title": "Article 17",
"description": "ir duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, w",
"image": "https://main--pricefx-eds--pricefx.hlx.live/learning-center/media_11996b9ef72021a10feff7cea83066a75572b7ef3.png?width=1200&format=pjpg&optimize=medium",
"imageAlt": "Article Image Alt",
"topics": "pricefx:industry/chemicals, pricefx:industry/consumer-products, pricefx:industry/discrete",
"authors": "pricefx:author/ann-cederhall, pricefx:author/atte-roine",
"category": "pricefx:category/chemicals, pricefx:category/distribution, pricefx:category/sales-and-marketing",
"readingTime": "9",
"articlePublishDate": "June 22, 2024",
"type": "",
"cq-tags": "pricefx:content-types/videos",
"lastPublished": "2024-04-30T05:26:34.889Z"

1. The Eyebrow text above the Card title should get the copy from `cq-tags`? Or is it still `category` but we have to look for `pricefx:content-types/` suffix only? Then we should only display the 1st value.....
2. Filter by Content Type should filter through `category` with `pricefx:content-types/` suffix or `cq-tags`?
3. The other filters (Filter by Industry/Role/Pricefx) need to filter through the `topics` key only? No need to include `category`, `cq-tags`?
4. Search should look through article's `category`, `title`, `description`, and `cq-tags`?
5. Should the `type` key be used anywhere in the Learning Center's logic?

**Comment by amogh-daryapurkar** [comment]
> @amogh-daryapurkar To make sure I'm understanding it correctly we can take this Article 17 as example:
> 
> ```
> {
> "path": "https://main--pricefx-eds--pricefx.hlx.page/learning-center/article-17",
> "lastModified": 1714454795,
> "title": "Article 17",
> "description": "ir duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, w",
> "image": "https://main--pricefx-eds--pricefx.hlx.live/learning-center/media_11996b9ef72021a10feff7cea83066a75572b7ef3.png?width=1200&format=pjpg&optimize=medium",
> "imageAlt": "Article Image Alt",
> "topics": "pricefx:industry/chemicals, pricefx:industry/consumer-products, pricefx:industry/discrete",
> "authors": "pricefx:author/ann-cederhall, pricefx:author/atte-roine",
> "category": "pricefx:category/chemicals, pricefx:category/distribution, pricefx:category/sales-and-marketing",
> "readingTime": "9",
> "articlePublishDate": "June 22, 2024",
> "type": "",
> "cq-tags": "pricefx:content-types/videos",
> "lastPublished": "2024-04-30T05:26:34.889Z"
> }
> ```
> 
> 1. The Eyebrow text above the Card title should get the copy from `cq-tags`? Or is it still `category` but we have to look for `pricefx:content-types/` suffix only? Then we should only display the 1st value.
> 2. Filter by Content Type should filter through `category` with `pricefx:content-types/` suffix or `cq-tags`?
> 3. The other filters (Filter by Industry/Role/Pricefx) need to filter through the `topics` key only? No need to include `category`, `cq-tags`?
> 4. Search should look through article's `category`, `title`, `description`, and `cq-tags`?
> 5. Should the `type` key be used anywhere in the Learning Center's logic?

@iSupercell We have asked Pricefx team to author only pricefx:content-types in category field to keep it clean. And I see the issue now with authoring, you can ignore my comment as I thought you were pulling it from cq:tags or topics. 

The search should happen on all the given fields.

Should the `type` key be used anywhere in the Learning Center's logic? - No

**Comment by amogh-daryapurkar** [comment]
Additionally, can you verify why the lighthouse is 83?

**Comment by amoghdaryapurkar** [comment]
@iSupercell I am approving it to unblock testing but I see an issue with Search not returning results accurately.

**Comment by amogh-daryapurkar** [comment]
@muneeskumar-rajendran can you have review it from your end?

**Review by SwathiPrasadRaju — APPROVED** [review]
FE Looks Good

**Review by SwathiPrasadRaju — APPROVED** [review]

**Review by SwathiPrasadRaju — APPROVED** [review]

**Review by muneeskumar-rajendran — APPROVED** [review]

**Review by amogh-daryapurkar — APPROVED** [review]

**Review by muneeskumar-rajendran — APPROVED** [review]

**Pull request merged**
